export const cheap = [
    {
        name: "dog",
        image: "./assets/img/dog.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "dog",
        image: "./assets/img/dog.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "cat",
        image: "./assets/img/cat.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "cat",
        image: "./assets/img/cat.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "fish",
        image: "./assets/img/fish.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "fish",
        image: "./assets/img/fish.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "lion",
        image: "./assets/img/lion.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "lion",
        image: "./assets/img/lion.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "monkey",
        image: "./assets/img/monkey.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "monkey",
        image: "./assets/img/monkey.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "mouse",
        image: "./assets/img/mouse.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "mouse",
        image: "./assets/img/mouse.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "pig",
        image: "./assets/img/pig.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "pig",
        image: "./assets/img/pig.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "shark",
        image: "./assets/img/shark.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "shark",
        image: "./assets/img/shark.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "turtle",
        image: "./assets/img/turtle.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "turtle",
        image: "./assets/img/turtle.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "crocodile",
        image: "./assets/img/crocodile.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "crocodile",
        image: "./assets/img/crocodile.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "panda",
        image: "./assets/img/panda.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "panda",
        image: "./assets/img/panda.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "penguin",
        image: "./assets/img/penguin.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
    {
        name: "penguin",
        image: "./assets/img/penguin.png",
        backImage: "./assets/img/memory.png",
        flip: false,
    },
];
